shunt.shunt.*:
  type: config_entity
  label: Shunt
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    description:
      type: string
      label: Description
